---
name: Build a new version of the app

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"
      - "**/__tests__/**"
      - ".prettierrc"

jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2


      - name: Get the app version from tags
        id: global_env
        run: |
          echo "::set-output name=APP_VERSION::$(git describe --abbrev=0)"

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install npm packages
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Builder"
          git config user.email "<>"

      - name: Commit the changes
        run: |
          git add dist
          git commit -m "BUILDER: Application build ${{steps.global_env.outputs.APP_VERSION}}"
          git push origin master
