---
name: Build a new version of the app

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "**/__tests__/**"
      - ".prettierrc"

jobs:
  build-application:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Get app version
        run: |
          git fetch --prune --unshallow --tags
          echo "::set-output name=APP_VERSION::$(git tag --sort=taggerdate | tail -1)"

      - name: Trigger building the app
        env:
          VERSION: ${{steps.global_env.outputs.APP_VERSION}}
        run: |
          echo "Trigger building app $VERSION"
          curl -X POST -u "${{ secrets.USERNAME }}:${{ secrets.PAT }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/jokernakartama/kcal-pwa-app/dispatches --data '{"event_type": "build_application", "client_payload": {"version": "$VERSION"}}'
